FROM dunglas/frankenphp

RUN install-php-extensions pdo_pgsql

RUN cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

WORKDIR /app

COPY Caddyfile /etc/caddy/Caddyfile
COPY . /app/public

ENV PORT=80

CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]